### ISSUE TITLE
new IE will have different extensions model

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/WebAccessibilityToolbar#59]
need figure out what this means for WAT http://www.neowin.net/news/internet-explorer-12-ui-overhaul-is-a-blend-of-chrome-and-firefox-adds-extension-support

> The other big change is that it appears, at least in the current setup, that the browser will support extensions like Chrome. While IE11 does support plugins, it’s not nearly as well developed as it is for Chrome where users can easily add items through Google’s extension store.

**Comment by matatk** [comment]
Just some thoughts...

This sounds very promising -- there are limitations to what WAT can do -- e.g. we are unable to re-use much code, because we can only run one script at a time, yet we do many things across scripts, such as check for a popup blocker.  Overall, having a proper extensions system will be great for WAT.  It will also make it easier to port WAT to other browsers, if we wanted to, as I'm sure the scripts will be written in JavaScript.

I suspect it would require the creation of a completely new extension, for which we'd need @jun325's help.  We would probably end up maintaining a legacy version of WAT (the now-current one) and the new one separately, though we could start by building on the code in this WAT (but then simplifying it to reduce duplication and improve robustness, as the new IE extensions framework allows).

**Comment by getterdone** [comment]
slightly in/out of topic but Why is there no WAT Chrome extension?

**Comment by ferllings** [comment]
@getterdone That's a work in progress: https://github.com/ThePacielloGroup/WATChrome
