### ISSUE TITLE
64-bit version still shows "32-bit" in the "About" menu

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/WebAccessibilityToolbar#78]
Not sure where this is set, but in the latest release, even though I installed the 64-bit version specifically, it shows "About - Accessibility Toolbar (32-bit)".

Seems the value is set by a variable somewhere (at compile time?)

``About=About - Accessibility Toolbar (%bitarch%-bit)``

![32bit-not-64bit](https://cloud.githubusercontent.com/assets/895831/6076933/845c7944-ade1-11e4-9651-d5abfd5a774b.png)

**Comment by matatk** [comment]
The reason is that even 64-bit IE runs in 32-bit mode by default.  There are two settings for determining how 64-bit it is; EPM and something else (not on Windows ATM so can't be sure).  I made a (relatively non-sensical) note to myself to document these two settings, and include their values in the UI, as I think Jun added the ability to probe them.  That note is #73, but we can keep both it and this one, to remind us to document it.

**Comment by patrickhlauke** [comment]
A quick fix alternative (unless we want to close this altogether, in light of Edge not supporting WAT in its current form) would be to simply drop "(32-bit)" from the menu item text...

**Comment by matatk** [comment]
@patrickhlauke: The 64-bit version includes a 32-bit version (so it's really a 64+32-bit version, which is a clarity issue we should address).  However I am not yet certain that what you're seeing is a bug -- as per [my comment above](https://github.com/ThePacielloGroup/WebAccessibilityToolbar/issues/78#issuecomment-73261911).  Could you confirm that you have put IE into 64-bit mode (using those two settings) and it's *still* showing as 32-bit?

**Comment by patrickhlauke** [comment]
i think it's confusing generally to users...does it add any value for them?

**Comment by matatk** [comment]
We've encountered a number of issues where people have thought that they were running IE in 64-bit mode but weren't (some of those people were me).  Having a clear indication of which mode IE (and therefore WAT) is in is important for both end-users and debugging.  We do need to improve the phrasing and the documentation, though.

**Comment by matatk** [comment]
P.S. If you do switch IE to 64-bit mode then that menu item will say it's in 64-bit mode (if that didn't come across in my previous messages then apologies for lack of clarity).  This is how the thing is a diagnostic/ tool (and therefore useful).

**Comment by matatk** [comment]
Just a thought... how about adding the number of bits as another 'diagnostic' menu entry below the 'Installed Version' one and not having it in the About option?  That would probably be much clearer.

So we could have something like: "Internet Explorer mode:" and then the number of bits below, as the last two menu 'options' -- would that be sufficiently clear do you think?

**Comment by patrickhlauke** [comment]
At this stage, not too fussed to be honest. Minor quibble though: as with the "Installed version" and the following item, e.g. "2015-05-20", I do question if these should be selectable menu items and not some form of static text (if such a construct is even possible in those menus)

**Comment by matatk** [comment]
I'd agree that it's "less than optimal" let's say to have these things in the menu -- the problem is that I don't think we're able to easily create new dialogs, and these menus are one place where we can insert he contents of variables by simply specifying the pattern in the appropriate .ini file.  So for the moment we can't really easily change that behaviour I'm sorry to say.  I can try to improve the wording, though.
